version: '3'
services:
  burgerorderer:
    build: ./BurgerOrderer
    ports:
      - "5000:5000"
    volumes:
      - ./BurgerOrderer:/app
      - ./MenuStore/menu.db:/app/menu.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  #to ensure the app runs in debug mode
    container_name: burgerorderer


  kitchenview:
    build: ./KitchenView
    command: python appk.py  
    ports:
      - "5001:5001"
    volumes:
      - ./KitchenView:/app
    container_name: kitchenview

  menustore:
    build: ./MenuStore
    volumes:
      - ./MenuStore:/app
      - ./MenuStore/menu.db:/app/menu.db
    container_name: menustore





# Build and run BurgerOrderer on port 5000 / Build and run KitchenView on port 5001.
# To build and start the containers: docker-compose up --build
# To stop containers: docker-compose down