version: '3'
services:
  burgerorderer:
    build: ./BurgerOrderer
    ports:
      - "5000:5000"
    volumes:
      - ./BurgerOrderer:/app
    container_name: burgerorderer

  kitchenview:
    build: ./KitchenView
    ports:
      - "5001:5001"
    volumes:
      - ./KitchenView:/app
    container_name: kitchenview

# Build and run BurgerOrderer on port 5000 / Build and run KitchenView on port 5001.
# To build and start the containers: docker-compose up --build
# To stop containers: docker-compose down